INSERT INTO genre
	(name)
VALUES 
	('Pop'),
	('Rock'),
	('Hip Hop/Rap'),
	('R&B'),
	('Country'),
	('Electronic/Dance'),
	('Jazz'),
	('Blues'),
	('Reggae'),
	('Latin'),
	('Folk'),
	('Metal'),
	('Punk'),
	('Classical'),
	('Alternative'),
	('Experimental'),
	('World Music'),
	('Soundtracks'),
	('New Age'),
	('Trap'),
	('Grime'),
	('Drill'),
	('K-Pop (Korean Pop)'),
	('J-Pop (Japanese Pop)'),
	('Afrobeat'),
	('Bollywood'),
	('Cumbia'),
	('Soca'),
	('Gospel'),
	('Christian Rock'),
	('Ska'),
	('Swing'),
	('Big Band'),
	('Lounge'),
	('Lo-fi'),
	('Vaporwave'),
	('Chiptune'),
	('Synthwave'),
	('Disco'),
	('House'),
	('Techno'),
	('Trance'),
	('Dubstep'),
	('Drum and Bass'),
	('Ambient');