INSERT INTO artist
	(artist_id, genre_id, name, bio_desc)
VALUES
	(1, 5, 'Brianna Sterling', 'Hailing from a small town in Tennessee, Brianna Sterling grew up with a guitar in hand and a voice that echoes the soulful tales of country living. Her debut album "Southern Skies" hit the charts with heartfelt ballads and foot-stomping anthems that capture the essence of rural America.'),
	(2, 4, 'Malikah', 'Malikah emerged from the vibrant streets of New Orleans, blending silky-smooth vocals with modern beats that define her unique brand of R&B. Her breakout single "Midnight Dreams" is a sultry ode to love and longing, showcasing her talent for crafting seductive melodies.'),
	(3, 23, 'Jinwoo', 'Jinwoo, the charismatic leader of the K-pop sensation "Luminous," has captivated global audiences with his electrifying dance moves and magnetic stage presence. Known for his versatile vocal range and trend-setting fashion sense, Jinwoo continues to push boundaries in the world of Korean pop music.'),
	(4, 10, 'Elana Castillo', 'Elena Castillo, the fiery songstress from Havana, infuses traditional Cuban rhythms with modern pop sensibilities. Her album "Azúcar y Pasión" has become a sensation across Latin America, celebrating the rich cultural heritage of her homeland with infectious beats and passionate lyrics.'),
	(5, 15, 'Echo Bloom', 'Echo Bloom, the enigmatic frontman of the indie band "Silent Echoes," crafts haunting melodies that blur the lines between dreamy introspection and raw emotion. With their debut album "Whispers in the Dark," Echo Bloom invites listeners into a sonic landscape where every note resonates with mystery and melancholy.'),
	(6, 29, 'Grace Divine', 'Grace Divine, born in the heart of Mississippi, spreads the message of faith and redemption through her powerful gospel vocals. Her uplifting anthem "Heaven''s Embrace" has become a beacon of hope for listeners around the world, reminding them of the transformative power of spirituality.'),
	(7, 7, 'Lucian Miles', 'Lucian Miles, the smooth jazz maestro from New York City, weaves intricate melodies on his saxophone that transport audiences to smoky jazz clubs of the past. With his album "Moonlit Serenade," Lucian Miles continues to redefine contemporary jazz with his soulful improvisations and timeless compositions.'),
	(8, 41, 'Sierra Rain', 'Sierra Rain, the electronic music prodigy from Berlin, creates pulsating beats and hypnotic rhythms that dominate the underground techno scene. Her experimental soundscapes and relentless energy on stage have earned her a dedicated following, making her a force to be reckoned with in the world of electronic dance music.'),
	(9, 9, 'Kairos', 'Kairos, the reggae sensation from Kingston, Jamaica, brings a message of unity and positivity through his laid-back grooves and infectious melodies. With his album "Island Vibes," Kairos spreads sunshine and good vibes wherever he goes, embodying the spirit of Caribbean music with every strum of his guitar.'),
	(10, 1, 'Lola Cruz', 'Lola Cruz, the pop princess from Los Angeles, dazzles audiences with her catchy hooks and energetic performances. Her debut single "Starlight Avenue" skyrocketed up the charts, cementing her place as one of pop music''s brightest rising stars with her infectious optimism and undeniable charisma.');